name: mkv-blockchain
layout_spectrum: 0.2110991624649614
typography_spectrum: 0.2183811
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.02570916735567153
  lightness: 0.4595278
  saturation: 0.618887
  rhythmicContrast: 0.9005059
purpose: []
title: ''
description: ''
author: {}
content_rating:
  adult: false
content: []
github: true
