name: mkv-blockchain
favicon: null
layout_spectrum: 0.2110991624649614
typography_spectrum: 0.4898058995604515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.025709167355671525
  lightness: 0.6759347578044981
  saturation: 0.3461801428347826
  rhythmicContrast: 0.8652042739558965
purpose: []
